# make table with first day and last day of recording

library(data.table)


dates = seq.Date(as.Date("2020-03-22"), last.day, by = "day")

json.states = data.table(code = c(     "AZ",
                                       "CA",
                                       "DE",
                                       "IN",
                                       "KS",
                                       "KY",
                                       "LA",
                                       "IA",
                                       "IL",
                                       "MO",
                                       "NC",
                                       "SC",
                                       "ND",
                                       "OK",
                                       "VT", 
                                       "MD",
                                       "MS", 
                                       "MA",
                                       "NYC",
                                       "NJ",
                                       "FL",
                                       "MI",
                                       "NV",
                                       "NH",
                                       "OR",
                                       "PA",
                                       "WA",
                                       "AL",
                                       "DC",
                                       "UT",
                                       "WY",
                                       "HI",
                                       "CO"),
                         
                         name = c("arizona",
                                  "california",
                                  "delaware",
                                  "indiana",
                                  "kansas",
                                  "kentucky",
                                  "louisiana",
                                  "iowa",
                                  "illinois",
                                  "missouri",
                                  "NorthCarolina",
                                  "SouthCarolina",
                                  "NorthDakota",
                                  "oklahoma",
                                  "vermont",
                                  "maryland",
                                  "mississippi",
                                  "ma",
                                  "nyc",
                                  "new_jersey",
                                  "florida",
                                  "michigan",
                                  "nevada",
                                  "new_hampshire",
                                  "oregon",
                                  "pennsylvania",
                                  "washington",
                                  "alabama",
                                  "doc",
                                  "utah",
                                  "wyoming",
                                  "hawaii",
                                  "colorado"
                                  
                         ),
                         state_name = c("Arizona",
                                  "California",
                                  "Delaware",
                                  "Indiana",
                                  "Kansas",
                                  "Kentucky",
                                  "Louisiana",
                                  "Iowa",
                                  "Illinois",
                                  "Missouri",
                                  "North Carolina",
                                  "South Carolina",
                                  "North Dakota",
                                  "Oklahoma",
                                  "Vermont",
                                  "Maryland",
                                  "Mississippi",
                                  "Massachusetts",
                                  "New York City",
                                  "New Jersey",
                                  "Florida",
                                  "Michigan",
                                  "Nevada",
                                  "New Hampshire",
                                  "Oregon",
                                  "Pennsylvania",
                                  "Washington",
                                  "Alabama",
                                  "District of Columbia",
                                 "Utah",
                                 "Wyoming",
                                 "Hawaii",
                                 "Colorado"
                                  
                         ),
                         json = 1)

other.states = data.table(code = c("GA", 
                                   "TX", 
                                   "CDC",
                                   "ID",
                                   "CT",
                               "AK",
                               "RI",
                               "TN",
                               "ME",
                               "WI",
                               "NM",
                               "VA"),
                               name = c("georgia",
                                       "texas",
                                       "cdc",
                                       "idaho",
                                       "connecticut",
                            "alaska",
                            "rhode_island",
                            "tennessee",
                            "maine",
                            "wisconsin",
                            "new mexico",
                            "virginia"),
                          state_name = c("Georgia",
                                         "Texas",
                                         "CDC",
                                         "Idaho",
                                         "Connecticut",
                                         "Alaska",
                                         "Rhode Island",
                                         "Tennessee",
                                        "Maine",
                                        "Wisconsin",
                                        "New Mexico",
                                        "Virginia"),
                              json=0)

table.states = rbind(json.states, other.states) 


