# make table with first day and last day of recording

library(data.table)

json.states = data.table(code = c(     "AZ",
                                       "CA",
                                       "DE",
                                       "IN",
                                       "KS",
                                       "KY",
                                       "LA",
                                       "IA",
                                       "IL",
                                       "MO",
                                       "NC",
                                       "SC",
                                       "ND",
                                       "OK",
                                       "VT", 
                                       "MD",
                                       "MS", 
                                       "MA",
                                       "NYC",
                                       "NJ"),
                         
                         name = c("arizona",
                                  "california",
                                  "delaware",
                                  "indiana",
                                  "kansas",
                                  "kentucky",
                                  "louisiana",
                                  "iowa",
                                  "illinois",
                                  "missouri",
                                  "NorthCarolina",
                                  "SouthCarolina",
                                  "NorthDakota",
                                  "oklahoma",
                                  "vermont",
                                  "maryland",
                                  "mississippi",
                                  "ma",
                                  "nyc",
                                  "new_jersey"
                                  
                         ),
                         state_name = c("Arizona",
                                  "California",
                                  "Delaware",
                                  "Indiana",
                                  "Kansas",
                                  "Kentucky",
                                  "Louisiana",
                                  "Iowa",
                                  "Illinois",
                                  "Missouri",
                                  "North Carolina",
                                  "South Carolina",
                                  "North Dakota",
                                  "Oklahoma",
                                  "Vermont",
                                  "Maryland",
                                  "Mississippi",
                                  "Massachusetts",
                                  "New York",
                                  "New Jersey"
                                  
                         ),
                        
                         first.day = as.Date(c(
                           "2020-05-13",
                           "2020-05-13",
                           "2020-05-12",
                           "2020-05-13",
                           "2020-05-13",
                           "2020-05-13",
                           "2020-05-12",
                           "2020-05-13",
                           "2020-05-14",
                           "2020-05-13",
                           "2020-05-13",
                           "2020-05-14",
                           "2020-05-14",
                           "2020-05-13",
                           "2020-05-13",
                           "2020-05-14",
                           "2020-05-12",
                           "2020-04-20",
                           "2020-04-14",
                           "2020-05-06")),
                         last.day = c(last.day,
                                      last.day,
                                      last.day,
                                      last.day,
                                      last.day-1,
                                      last.day,
                                      last.day,
                                      last.day,
                                      last.day,
                                      last.day,
                                      last.day,
                                      last.day,
                                      last.day,
                                      last.day,
                                      last.day,
                                      last.day,
                                      last.day,
                                      last.day,
                                      last.day-3,
                                      last.day-3
                                      
                         ),
                         json = 1)

other.states = data.table(code = c("GA", 
                               #    "NY", 
                                   "TX", 
                                   "FL", 
                                   "CDC",
                                   "ID",
                                   "CT",
                                   "CO"),
                              name = c("georgia",
                            #           "New York",
                                       "texas",
                                       "florida",
                                       "cdc",
                                       "idaho",
                                       "connecticut",
                                       "colorado"),
                          state_name = c("Georgia",
                                         #           "New York",
                                         "Texas",
                                         "Florida",
                                         "CDC",
                                         "Idaho",
                                         "Connecticut",
                                         "Colorado"),
                          
                              first.day = as.Date(c("2020-05-07", 
                                #                    "2020-05-07", 
                                                    "2020-05-06", 
                                                    "2020-03-27", 
                                                    "2020-05-06",
                                                    "2020-05-13",
                                                    "2020-05-11",
                                                    "2020-05-12")), 
                          last.day = c(last.day-2,
                                 #      last.day,
                                       last.day-2,
                                       last.day-2,
                                       last.wednesday,
                                       last.day,
                                       last.day-3,
                                       last.day-2
                                       
                          ),
                              json=0)

table.states = rbind(json.states, other.states)
