name: Run daily update
on:
  schedule:
<<<<<<< HEAD
    - cron: "18 20 * * *"
    - cron: "48 22 * * *"
=======
    - cron: "08 23 * * *"
    - cron: "40 20 * * *"
>>>>>>> 79f27dcfaecb79581e8797d83af7bb7d17a41edd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
   
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
<<<<<<< HEAD

=======
        
    - name: Install R 
      run: |
        sudo apt install r-base
        
>>>>>>> 79f27dcfaecb79581e8797d83af7bb7d17a41edd
    - name: Install Chromium
      run: |
        sudo apt-get update
        sudo apt-get install chromium-browser

    - name: Clone data from yesterday
      run: |
<<<<<<< HEAD
        git clone https://@github.com/MJHutchinson/US-covid19-data-scraping --single-branch -b update_data output 
=======
        git clone https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/MJHutchinson/US-covid19-data-scraping --single-branch -b update_data output 
>>>>>>> 79f27dcfaecb79581e8797d83af7bb7d17a41edd
        git config --global user.name "GitHub Actions"
        git config --global user.email action@github.com

    - name: Update Data Sources
      run: |
        make files
        today=$(date +'%Y-%m-%d')
<<<<<<< HEAD
        
        # check the data for today is there already
        if [ -d "output/data/$today" ]; then
          cp data/$today/* output/data/$today
        else
          mv data/$today output/data/
        fi
        
=======
        cp -a data/. output/data/
>>>>>>> 79f27dcfaecb79581e8797d83af7bb7d17a41edd
        cp -a html/. output/html/
        cp -a csvs/. output/csvs/
        cp -a pngs/. output/pngs/

        cd output
        git add -f .
        git status
        git commit -m "Automated data update"
        git push \
          "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/MJHutchinson/US-covid19-data-scraping" \
          HEAD:update_data
<<<<<<< HEAD
=======
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
>>>>>>> 79f27dcfaecb79581e8797d83af7bb7d17a41edd
